// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Temperature.proto

package ds.Temperature;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Temperature.Empty)
    com.google.protobuf.MessageOrBuilder {
}
