// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Temperature.proto

package ds.Temperature;

public interface SetRoomTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Temperature.SetRoomTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 room_id = 1;</code>
   */
  int getRoomId();

  /**
   * <code>float temperature = 2;</code>
   */
  float getTemperature();
}
