// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Temperature.proto

package ds.Temperature;

public interface TemperatureAutomationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Temperature.TemperatureAutomationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 room_id = 1;</code>
   */
  int getRoomId();

  /**
   * <code>int32 hour = 2;</code>
   */
  int getHour();

  /**
   * <code>float temperature = 3;</code>
   */
  float getTemperature();
}
