// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto

package ds.Storage;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Storage.Empty)
    com.google.protobuf.MessageOrBuilder {
}
