// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto

package ds.Storage;

public interface FileUploadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Storage.FileUploadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the file being uploaded
   * </pre>
   *
   * <code>int32 file_id = 1;</code>
   */
  int getFileId();
}
