// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto

package ds.Storage;

public interface FileUploadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Storage.FileUploadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the uploaded file
   * </pre>
   *
   * <code>int32 file_id = 1;</code>
   */
  int getFileId();

  /**
   * <pre>
   * Message indicating if the upload was successful
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Message indicating if the upload was successful
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
