// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto

package ds.Storage;

public interface FileDeleteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Storage.FileDeleteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Message indicating if the deletion was successful
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Message indicating if the deletion was successful
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
