// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto

package ds.Storage;

public interface FileDownloadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Storage.FileDownloadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Filename of the downloaded file
   * </pre>
   *
   * <code>string filename = 1;</code>
   */
  java.lang.String getFilename();
  /**
   * <pre>
   * Filename of the downloaded file
   * </pre>
   *
   * <code>string filename = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <pre>
   * Content of the downloaded file
   * </pre>
   *
   * <code>int32 content = 2;</code>
   */
  int getContent();

  /**
   * <pre>
   * Message indicating if the download was successful
   * </pre>
   *
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Message indicating if the download was successful
   * </pre>
   *
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
