// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto

package ds.Storage;

public interface FileUploadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Storage.FileUploadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Filename of the file being uploaded
   * </pre>
   *
   * <code>string filename = 1;</code>
   */
  java.lang.String getFilename();
  /**
   * <pre>
   * Filename of the file being uploaded
   * </pre>
   *
   * <code>string filename = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <pre>
   * Content of the file being uploaded
   * </pre>
   *
   * <code>int32 content = 2;</code>
   */
  int getContent();
}
