// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto

package ds.Storage;

public interface FileListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Storage.FileListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of uploaded file names
   * </pre>
   *
   * <code>string filenames = 1;</code>
   */
  java.lang.String getFilenames();
  /**
   * <pre>
   * List of uploaded file names
   * </pre>
   *
   * <code>string filenames = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilenamesBytes();
}
