// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto

package ds.Storage;

public interface FileListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Storage.FileListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of uploaded file names
   * </pre>
   *
   * <code>int32 file_id = 1;</code>
   */
  int getFileId();

  /**
   * <code>string filename = 2;</code>
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 2;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>int32 content = 3;</code>
   */
  int getContent();
}
