// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto

package ds.Storage;

public final class StorageImpl {
  private StorageImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Storage_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Storage_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Storage_FileUploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Storage_FileUploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Storage_FileUploadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Storage_FileUploadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Storage_FileDownloadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Storage_FileDownloadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Storage_FileDownloadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Storage_FileDownloadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Storage_FileDeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Storage_FileDeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Storage_FileDeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Storage_FileDeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Storage_FileListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Storage_FileListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStorage.proto\022\007Storage\"\007\n\005Empty\"6\n\021Fil" +
      "eUploadRequest\022\020\n\010filename\030\001 \001(\t\022\017\n\007cont" +
      "ent\030\002 \001(\005\"6\n\022FileUploadResponse\022\017\n\007file_" +
      "id\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\"&\n\023FileDownloa" +
      "dRequest\022\017\n\007file_id\030\001 \001(\005\"J\n\024FileDownloa" +
      "dResponse\022\020\n\010filename\030\001 \001(\t\022\017\n\007content\030\002" +
      " \001(\005\022\017\n\007message\030\003 \001(\t\"$\n\021FileDeleteReque" +
      "st\022\017\n\007file_id\030\001 \001(\005\"%\n\022FileDeleteRespons" +
      "e\022\017\n\007message\030\001 \001(\t\"%\n\020FileListResponse\022\021" +
      "\n\tfilenames\030\001 \001(\t2\264\002\n\007Storage\022L\n\013UploadF" +
      "iles\022\032.Storage.FileUploadRequest\032\033.Stora" +
      "ge.FileUploadResponse\"\000(\0010\001\022R\n\rDownloadF" +
      "iles\022\034.Storage.FileDownloadRequest\032\035.Sto" +
      "rage.FileDownloadResponse\"\000(\0010\001\022G\n\nDelet" +
      "eFile\022\032.Storage.FileDeleteRequest\032\033.Stor" +
      "age.FileDeleteResponse\"\000\022>\n\017RequestFileL" +
      "ist\022\016.Storage.Empty\032\031.Storage.FileListRe" +
      "sponse\"\000B\033\n\nds.StorageB\013StorageImplP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Storage_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Storage_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Storage_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_Storage_FileUploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Storage_FileUploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Storage_FileUploadRequest_descriptor,
        new java.lang.String[] { "Filename", "Content", });
    internal_static_Storage_FileUploadResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Storage_FileUploadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Storage_FileUploadResponse_descriptor,
        new java.lang.String[] { "FileId", "Message", });
    internal_static_Storage_FileDownloadRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Storage_FileDownloadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Storage_FileDownloadRequest_descriptor,
        new java.lang.String[] { "FileId", });
    internal_static_Storage_FileDownloadResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Storage_FileDownloadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Storage_FileDownloadResponse_descriptor,
        new java.lang.String[] { "Filename", "Content", "Message", });
    internal_static_Storage_FileDeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Storage_FileDeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Storage_FileDeleteRequest_descriptor,
        new java.lang.String[] { "FileId", });
    internal_static_Storage_FileDeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Storage_FileDeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Storage_FileDeleteResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_Storage_FileListResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Storage_FileListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Storage_FileListResponse_descriptor,
        new java.lang.String[] { "Filenames", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
