// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lighting.proto

package ds.Lighting;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Lighting.Empty)
    com.google.protobuf.MessageOrBuilder {
}
