// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lighting.proto

package ds.Lighting;

public final class LightingImpl {
  private LightingImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lighting_RoomLightingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lighting_RoomLightingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lighting_RoomLightingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lighting_RoomLightingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lighting_LightingAutomationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lighting_LightingAutomationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lighting_LightingAutomationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lighting_LightingAutomationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lighting_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lighting_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lighting_LightingStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lighting_LightingStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Lighting.proto\022\010Lighting\"\204\001\n\023RoomLight" +
      "ingRequest\022\017\n\007room_id\030\001 \001(\t\022:\n\005state\030\002 \001" +
      "(\0162+.Lighting.RoomLightingRequest.Lighti" +
      "ngState\" \n\rLightingState\022\006\n\002ON\020\000\022\007\n\003OFF\020" +
      "\001\"8\n\024RoomLightingResponse\022\017\n\007success\030\001 \001" +
      "(\010\022\017\n\007message\030\002 \001(\t\"J\n\031LightingAutomatio" +
      "nRequest\022\014\n\004hour\030\001 \001(\005\022\016\n\006minute\030\002 \001(\005\022\017" +
      "\n\007turn_on\030\003 \001(\010\">\n\032LightingAutomationRes" +
      "ponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"" +
      "\007\n\005Empty\"8\n\026LightingStatusResponse\022\017\n\007ro" +
      "om_id\030\001 \001(\t\022\r\n\005is_on\030\002 \001(\0102\224\002\n\017LightingS" +
      "ervice\022P\n\017SetRoomLighting\022\035.Lighting.Roo" +
      "mLightingRequest\032\036.Lighting.RoomLighting" +
      "Response\022a\n\022LightingAutomation\022#.Lightin" +
      "g.LightingAutomationRequest\032$.Lighting.L" +
      "ightingAutomationResponse(\001\022L\n\025LightingS" +
      "tatusRequest\022\017.Lighting.Empty\032 .Lighting" +
      ".LightingStatusResponse0\001B\035\n\013ds.Lighting" +
      "B\014LightingImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Lighting_RoomLightingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Lighting_RoomLightingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lighting_RoomLightingRequest_descriptor,
        new java.lang.String[] { "RoomId", "State", });
    internal_static_Lighting_RoomLightingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Lighting_RoomLightingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lighting_RoomLightingResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_Lighting_LightingAutomationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Lighting_LightingAutomationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lighting_LightingAutomationRequest_descriptor,
        new java.lang.String[] { "Hour", "Minute", "TurnOn", });
    internal_static_Lighting_LightingAutomationResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Lighting_LightingAutomationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lighting_LightingAutomationResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_Lighting_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Lighting_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lighting_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_Lighting_LightingStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Lighting_LightingStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lighting_LightingStatusResponse_descriptor,
        new java.lang.String[] { "RoomId", "IsOn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
