// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lighting.proto

package ds.Lighting;

public final class LightingImpl {
  private LightingImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lighting_SetRoomLightingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lighting_SetRoomLightingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lighting_SetRoomLightingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lighting_SetRoomLightingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lighting_LightingAutomationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lighting_LightingAutomationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lighting_LightingAutomationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lighting_LightingAutomationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lighting_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lighting_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lighting_LightingStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lighting_LightingStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Lighting.proto\022\010Lighting\"8\n\026SetRoomLig" +
      "htingRequest\022\017\n\007room_id\030\001 \001(\005\022\r\n\005is_on\030\002" +
      " \001(\010\";\n\027SetRoomLightingResponse\022\017\n\007succe" +
      "ss\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"K\n\031LightingAut" +
      "omationRequest\022\017\n\007room_id\030\001 \001(\005\022\014\n\004hour\030" +
      "\002 \001(\005\022\017\n\007turn_on\030\003 \001(\010\">\n\032LightingAutoma" +
      "tionResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message" +
      "\030\002 \001(\t\"\007\n\005Empty\"8\n\026LightingStatusRespons" +
      "e\022\017\n\007room_id\030\001 \001(\t\022\r\n\005is_on\030\002 \001(\0102\232\002\n\017Li" +
      "ghtingService\022V\n\017SetRoomLighting\022 .Light" +
      "ing.SetRoomLightingRequest\032!.Lighting.Se" +
      "tRoomLightingResponse\022a\n\022LightingAutomat" +
      "ion\022#.Lighting.LightingAutomationRequest" +
      "\032$.Lighting.LightingAutomationResponse(\001" +
      "\022L\n\025LightingStatusRequest\022\017.Lighting.Emp" +
      "ty\032 .Lighting.LightingStatusResponse0\001B\035" +
      "\n\013ds.LightingB\014LightingImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Lighting_SetRoomLightingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Lighting_SetRoomLightingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lighting_SetRoomLightingRequest_descriptor,
        new java.lang.String[] { "RoomId", "IsOn", });
    internal_static_Lighting_SetRoomLightingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Lighting_SetRoomLightingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lighting_SetRoomLightingResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_Lighting_LightingAutomationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Lighting_LightingAutomationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lighting_LightingAutomationRequest_descriptor,
        new java.lang.String[] { "RoomId", "Hour", "TurnOn", });
    internal_static_Lighting_LightingAutomationResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Lighting_LightingAutomationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lighting_LightingAutomationResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_Lighting_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Lighting_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lighting_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_Lighting_LightingStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Lighting_LightingStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lighting_LightingStatusResponse_descriptor,
        new java.lang.String[] { "RoomId", "IsOn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
