// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lighting.proto

package ds.Lighting;

public interface LightingAutomationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Lighting.LightingAutomationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 hour = 1;</code>
   */
  int getHour();

  /**
   * <code>int32 minute = 2;</code>
   */
  int getMinute();

  /**
   * <code>bool turn_on = 3;</code>
   */
  boolean getTurnOn();
}
