// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lighting.proto

package ds.Lighting;

public interface LightingStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Lighting.LightingStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 room_id = 1;</code>
   */
  int getRoomId();

  /**
   * <code>bool is_on = 2;</code>
   */
  boolean getIsOn();
}
