// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lighting.proto

package ds.Lighting;

public interface RoomLightingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Lighting.RoomLightingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string room_id = 1;</code>
   */
  java.lang.String getRoomId();
  /**
   * <code>string room_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();

  /**
   * <code>.Lighting.RoomLightingRequest.LightingState state = 2;</code>
   */
  int getStateValue();
  /**
   * <code>.Lighting.RoomLightingRequest.LightingState state = 2;</code>
   */
  ds.Lighting.RoomLightingRequest.LightingState getState();
}
