// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lighting.proto

package ds.Lighting;

public interface SetRoomLightingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Lighting.SetRoomLightingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string room_id = 1;</code>
   */
  java.lang.String getRoomId();
  /**
   * <code>string room_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();

  /**
   * <code>.Lighting.SetRoomLightingRequest.LightingState state = 2;</code>
   */
  int getStateValue();
  /**
   * <code>.Lighting.SetRoomLightingRequest.LightingState state = 2;</code>
   */
  ds.Lighting.SetRoomLightingRequest.LightingState getState();
}
