// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OfficeLightingControl.proto

package ds.OfficeLightingControl;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OfficeLightingControl.Empty)
    com.google.protobuf.MessageOrBuilder {
}
