// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OfficeLightingControl.proto

package ds.OfficeLightingControl;

public interface LightingStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OfficeLightingControl.LightingStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string room_id = 1;</code>
   */
  java.lang.String getRoomId();
  /**
   * <code>string room_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();

  /**
   * <code>bool is_on = 2;</code>
   */
  boolean getIsOn();
}
