// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OfficeLightingControl.proto

package ds.OfficeLightingControl;

public interface LightingSettingsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OfficeLightingControl.LightingSettingsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 hour = 1;</code>
   */
  int getHour();

  /**
   * <code>int32 minute = 2;</code>
   */
  int getMinute();

  /**
   * <code>bool turn_on = 3;</code>
   */
  boolean getTurnOn();
}
