// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OfficeLightingControl.proto

package ds.OfficeLightingControl;

public final class OfficeLightingControlImpl {
  private OfficeLightingControlImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OfficeLightingControl_RoomLightingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OfficeLightingControl_RoomLightingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OfficeLightingControl_RoomLightingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OfficeLightingControl_RoomLightingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OfficeLightingControl_LightingSettingsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OfficeLightingControl_LightingSettingsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OfficeLightingControl_LightingAutomationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OfficeLightingControl_LightingAutomationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OfficeLightingControl_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OfficeLightingControl_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OfficeLightingControl_LightingStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OfficeLightingControl_LightingStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033OfficeLightingControl.proto\022\025OfficeLig" +
      "htingControl\"\221\001\n\023RoomLightingRequest\022\017\n\007" +
      "room_id\030\001 \001(\t\022G\n\005state\030\002 \001(\01628.OfficeLig" +
      "htingControl.RoomLightingRequest.Lightin" +
      "gState\" \n\rLightingState\022\006\n\002ON\020\000\022\007\n\003OFF\020\001" +
      "\"8\n\024RoomLightingResponse\022\017\n\007success\030\001 \001(" +
      "\010\022\017\n\007message\030\002 \001(\t\"H\n\027LightingSettingsRe" +
      "quest\022\014\n\004hour\030\001 \001(\005\022\016\n\006minute\030\002 \001(\005\022\017\n\007t" +
      "urn_on\030\003 \001(\010\">\n\032LightingAutomationRespon" +
      "se\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"\007\n\005" +
      "Empty\"8\n\026LightingStatusResponse\022\017\n\007room_" +
      "id\030\001 \001(\t\022\r\n\005is_on\030\002 \001(\0102\367\002\n\034OfficeLighti" +
      "ngControlService\022j\n\017SetRoomLighting\022*.Of" +
      "ficeLightingControl.RoomLightingRequest\032" +
      "+.OfficeLightingControl.RoomLightingResp" +
      "onse\022\202\001\n\033TimeBasedLightingAutomation\022..O" +
      "fficeLightingControl.LightingSettingsReq" +
      "uest\0321.OfficeLightingControl.LightingAut" +
      "omationResponse(\001\022f\n\025LightingStatusReque" +
      "st\022\034.OfficeLightingControl.Empty\032-.Offic" +
      "eLightingControl.LightingStatusResponse0" +
      "\001B7\n\030ds.OfficeLightingControlB\031OfficeLig" +
      "htingControlImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OfficeLightingControl_RoomLightingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OfficeLightingControl_RoomLightingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OfficeLightingControl_RoomLightingRequest_descriptor,
        new java.lang.String[] { "RoomId", "State", });
    internal_static_OfficeLightingControl_RoomLightingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OfficeLightingControl_RoomLightingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OfficeLightingControl_RoomLightingResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_OfficeLightingControl_LightingSettingsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OfficeLightingControl_LightingSettingsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OfficeLightingControl_LightingSettingsRequest_descriptor,
        new java.lang.String[] { "Hour", "Minute", "TurnOn", });
    internal_static_OfficeLightingControl_LightingAutomationResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_OfficeLightingControl_LightingAutomationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OfficeLightingControl_LightingAutomationResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_OfficeLightingControl_Empty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_OfficeLightingControl_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OfficeLightingControl_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_OfficeLightingControl_LightingStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_OfficeLightingControl_LightingStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OfficeLightingControl_LightingStatusResponse_descriptor,
        new java.lang.String[] { "RoomId", "IsOn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
