// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OfficeLightingControl.proto

package ds.OfficeLightingControl;

/**
 * Protobuf type {@code OfficeLightingControl.RoomLightingRequest}
 */
public  final class RoomLightingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OfficeLightingControl.RoomLightingRequest)
    RoomLightingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RoomLightingRequest.newBuilder() to construct.
  private RoomLightingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RoomLightingRequest() {
    roomId_ = "";
    state_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RoomLightingRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            roomId_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            state_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.OfficeLightingControl.OfficeLightingControlImpl.internal_static_OfficeLightingControl_RoomLightingRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.OfficeLightingControl.OfficeLightingControlImpl.internal_static_OfficeLightingControl_RoomLightingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.OfficeLightingControl.RoomLightingRequest.class, ds.OfficeLightingControl.RoomLightingRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code OfficeLightingControl.RoomLightingRequest.LightingState}
   */
  public enum LightingState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ON = 0;</code>
     */
    ON(0),
    /**
     * <code>OFF = 1;</code>
     */
    OFF(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ON = 0;</code>
     */
    public static final int ON_VALUE = 0;
    /**
     * <code>OFF = 1;</code>
     */
    public static final int OFF_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LightingState valueOf(int value) {
      return forNumber(value);
    }

    public static LightingState forNumber(int value) {
      switch (value) {
        case 0: return ON;
        case 1: return OFF;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LightingState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LightingState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LightingState>() {
            public LightingState findValueByNumber(int number) {
              return LightingState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ds.OfficeLightingControl.RoomLightingRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final LightingState[] VALUES = values();

    public static LightingState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LightingState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:OfficeLightingControl.RoomLightingRequest.LightingState)
  }

  public static final int ROOM_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object roomId_;
  /**
   * <code>string room_id = 1;</code>
   */
  public java.lang.String getRoomId() {
    java.lang.Object ref = roomId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roomId_ = s;
      return s;
    }
  }
  /**
   * <code>string room_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRoomIdBytes() {
    java.lang.Object ref = roomId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roomId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATE_FIELD_NUMBER = 2;
  private int state_;
  /**
   * <code>.OfficeLightingControl.RoomLightingRequest.LightingState state = 2;</code>
   */
  public int getStateValue() {
    return state_;
  }
  /**
   * <code>.OfficeLightingControl.RoomLightingRequest.LightingState state = 2;</code>
   */
  public ds.OfficeLightingControl.RoomLightingRequest.LightingState getState() {
    @SuppressWarnings("deprecation")
    ds.OfficeLightingControl.RoomLightingRequest.LightingState result = ds.OfficeLightingControl.RoomLightingRequest.LightingState.valueOf(state_);
    return result == null ? ds.OfficeLightingControl.RoomLightingRequest.LightingState.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRoomIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, roomId_);
    }
    if (state_ != ds.OfficeLightingControl.RoomLightingRequest.LightingState.ON.getNumber()) {
      output.writeEnum(2, state_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRoomIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, roomId_);
    }
    if (state_ != ds.OfficeLightingControl.RoomLightingRequest.LightingState.ON.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, state_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.OfficeLightingControl.RoomLightingRequest)) {
      return super.equals(obj);
    }
    ds.OfficeLightingControl.RoomLightingRequest other = (ds.OfficeLightingControl.RoomLightingRequest) obj;

    boolean result = true;
    result = result && getRoomId()
        .equals(other.getRoomId());
    result = result && state_ == other.state_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROOM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRoomId().hashCode();
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.OfficeLightingControl.RoomLightingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.OfficeLightingControl.RoomLightingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.OfficeLightingControl.RoomLightingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.OfficeLightingControl.RoomLightingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.OfficeLightingControl.RoomLightingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.OfficeLightingControl.RoomLightingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.OfficeLightingControl.RoomLightingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.OfficeLightingControl.RoomLightingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.OfficeLightingControl.RoomLightingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.OfficeLightingControl.RoomLightingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.OfficeLightingControl.RoomLightingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.OfficeLightingControl.RoomLightingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.OfficeLightingControl.RoomLightingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code OfficeLightingControl.RoomLightingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OfficeLightingControl.RoomLightingRequest)
      ds.OfficeLightingControl.RoomLightingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.OfficeLightingControl.OfficeLightingControlImpl.internal_static_OfficeLightingControl_RoomLightingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.OfficeLightingControl.OfficeLightingControlImpl.internal_static_OfficeLightingControl_RoomLightingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.OfficeLightingControl.RoomLightingRequest.class, ds.OfficeLightingControl.RoomLightingRequest.Builder.class);
    }

    // Construct using ds.OfficeLightingControl.RoomLightingRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      roomId_ = "";

      state_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.OfficeLightingControl.OfficeLightingControlImpl.internal_static_OfficeLightingControl_RoomLightingRequest_descriptor;
    }

    @java.lang.Override
    public ds.OfficeLightingControl.RoomLightingRequest getDefaultInstanceForType() {
      return ds.OfficeLightingControl.RoomLightingRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.OfficeLightingControl.RoomLightingRequest build() {
      ds.OfficeLightingControl.RoomLightingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.OfficeLightingControl.RoomLightingRequest buildPartial() {
      ds.OfficeLightingControl.RoomLightingRequest result = new ds.OfficeLightingControl.RoomLightingRequest(this);
      result.roomId_ = roomId_;
      result.state_ = state_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.OfficeLightingControl.RoomLightingRequest) {
        return mergeFrom((ds.OfficeLightingControl.RoomLightingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.OfficeLightingControl.RoomLightingRequest other) {
      if (other == ds.OfficeLightingControl.RoomLightingRequest.getDefaultInstance()) return this;
      if (!other.getRoomId().isEmpty()) {
        roomId_ = other.roomId_;
        onChanged();
      }
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.OfficeLightingControl.RoomLightingRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.OfficeLightingControl.RoomLightingRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object roomId_ = "";
    /**
     * <code>string room_id = 1;</code>
     */
    public java.lang.String getRoomId() {
      java.lang.Object ref = roomId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string room_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoomIdBytes() {
      java.lang.Object ref = roomId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string room_id = 1;</code>
     */
    public Builder setRoomId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roomId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string room_id = 1;</code>
     */
    public Builder clearRoomId() {
      
      roomId_ = getDefaultInstance().getRoomId();
      onChanged();
      return this;
    }
    /**
     * <code>string room_id = 1;</code>
     */
    public Builder setRoomIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roomId_ = value;
      onChanged();
      return this;
    }

    private int state_ = 0;
    /**
     * <code>.OfficeLightingControl.RoomLightingRequest.LightingState state = 2;</code>
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <code>.OfficeLightingControl.RoomLightingRequest.LightingState state = 2;</code>
     */
    public Builder setStateValue(int value) {
      state_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.OfficeLightingControl.RoomLightingRequest.LightingState state = 2;</code>
     */
    public ds.OfficeLightingControl.RoomLightingRequest.LightingState getState() {
      @SuppressWarnings("deprecation")
      ds.OfficeLightingControl.RoomLightingRequest.LightingState result = ds.OfficeLightingControl.RoomLightingRequest.LightingState.valueOf(state_);
      return result == null ? ds.OfficeLightingControl.RoomLightingRequest.LightingState.UNRECOGNIZED : result;
    }
    /**
     * <code>.OfficeLightingControl.RoomLightingRequest.LightingState state = 2;</code>
     */
    public Builder setState(ds.OfficeLightingControl.RoomLightingRequest.LightingState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.OfficeLightingControl.RoomLightingRequest.LightingState state = 2;</code>
     */
    public Builder clearState() {
      
      state_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:OfficeLightingControl.RoomLightingRequest)
  }

  // @@protoc_insertion_point(class_scope:OfficeLightingControl.RoomLightingRequest)
  private static final ds.OfficeLightingControl.RoomLightingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.OfficeLightingControl.RoomLightingRequest();
  }

  public static ds.OfficeLightingControl.RoomLightingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RoomLightingRequest>
      PARSER = new com.google.protobuf.AbstractParser<RoomLightingRequest>() {
    @java.lang.Override
    public RoomLightingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RoomLightingRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RoomLightingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RoomLightingRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.OfficeLightingControl.RoomLightingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

