// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OfficeLightingControl.proto

package ds.OfficeLightingControl;

public interface RoomLightingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OfficeLightingControl.RoomLightingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string room_id = 1;</code>
   */
  java.lang.String getRoomId();
  /**
   * <code>string room_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();

  /**
   * <code>.OfficeLightingControl.RoomLightingRequest.LightingState state = 2;</code>
   */
  int getStateValue();
  /**
   * <code>.OfficeLightingControl.RoomLightingRequest.LightingState state = 2;</code>
   */
  ds.OfficeLightingControl.RoomLightingRequest.LightingState getState();
}
